Q1-Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,1])
print("Greater",np.greater(a,b))
print("Greater_equal",np.greater_equal(a,b))
print("Less",np.less(a,b))
print("Less_equal",np.less_equal(a,b))

Greater [False False  True]
Greater_equal [False False  True]
Less [ True  True False]
Less_equal [ True  True False]


Q2-Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
a=np.zeros(10)
b=np.ones(10)
c=5*np.ones(10)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Q3-Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [8]:
a=np.array([[1,2,3],[3,4,2]])
print("Sum of all elemnt",np.sum(a))
print("Sum of each column",np.sum(a,axis=0))
print("Sum of each row",np.sum(a,axis=1))

Sum of all elemnt 15
Sum of each column [4 6 5]
Sum of each row [6 9]


Q4-Write a NumPy program to add, subtract, multiply, divide arguments element-wise

In [9]:
print("Add:",np.add(1.0, 4.0))
print("Subtract:",np.subtract(1.0, 4.0))
print("Multiply:",np.multiply(1.0, 4.0))
print("Divide:",np.divide(1.0, 4.0))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


Q5-Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree

In [12]:
degree=np.array((0., 30., 45., 60., 90.))
print("sine:")
print(np.sin( degree* np.pi / 180.))
print("cosine:")
print(np.cos(degree * np.pi / 180.))
print("tangent:")
print(np.tan(degree * np.pi / 180.))

sine:
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Q6-Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [13]:
import pandas as pd
e={'name':['Rohan','Rahul','Sinchana','Mannu'],'roll no.':[11,22,33,44],'marks':[89,90,96,54]}
l=[1,2,3,4]
df=pd.DataFrame(e,index=l)
print(df)

       name  roll no.  marks
1     Rohan        11     89
2     Rahul        22     90
3  Sinchana        33     96
4     Mannu        44     54


Q7-Write a Pandas program to select the 'name' and 'marks' columns from the following DataFrame

In [16]:
print(df[['name','marks']])

       name  marks
1     Rohan     89
2     Rahul     90
3  Sinchana     96
4     Mannu     54


Q8-Write a Pandas program to join the two given dataframes along rows and assign all data

In [20]:
e1={'name':['Raj','Rakesh',np.nan,'Manny'],'roll no.':[34,np.nan,63,42],'marks':[81,40,np.nan,51]}
l1=[1,2,3,4]
df1=pd.DataFrame(e1,index=l1)
print(pd.concat([df,df1]))

       name  roll no.  marks
1     Rohan      11.0   89.0
2     Rahul      22.0   90.0
3  Sinchana      33.0   96.0
4     Mannu      44.0   54.0
1       Raj      34.0   81.0
2    Rakesh       NaN   40.0
3       NaN      63.0    NaN
4     Manny      42.0   51.0


Q9-Write a Pandas program to detect missing values of a given DataFrame. Display True or False.


In [21]:
print(df1.isnull())

    name  roll no.  marks
1  False     False  False
2  False      True  False
3   True     False   True
4  False     False  False


Q10-Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data

In [23]:
ds = pd.Series([22, 9, 2, 82, 1])
print(ds)

0    22
1     9
2     2
3    82
4     1
dtype: int64
